create table if not exists public.beta_tester_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  origem text not null default 'formulario-web',
  n8n_execution_id text,
  nome text not null,
  email text not null,
  whatsapp text not null,
  area_atuacao text not null,
  formatos_aula jsonb not null default '[]'::jsonb,
  tempo_atuacao text not null,
  alunos_mes text not null,
  renda_principal text not null,
  organizacao_atual jsonb not null default '[]'::jsonb,
  principal_dor text not null,
  problema_financeiro text not null,
  crescer_6_meses text not null,
  funcionalidades_desejadas jsonb not null default '[]'::jsonb,
  interesse_beta text not null,
  feedback_disponibilidade text not null,
  observacoes text,
  perfil text,
  prioridade text,
  score integer check (score between 0 and 10),
  resumo_ia text,
  mensagem_ia text,
  raw_payload jsonb not null default '{}'::jsonb
);

create index if not exists beta_tester_history_created_at_idx
  on public.beta_tester_history (created_at desc);

create index if not exists beta_tester_history_prioridade_idx
  on public.beta_tester_history (prioridade);

alter table public.beta_tester_history enable row level security;
